### ISSUE TITLE
Algunas mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-3-evaluacion-intermedia-AnadelaJara#1]
Buen trabajo @AnadelaJara  !

### Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Si utilizas SASS, recuerda instalarlo y grabarlo en el `package.json` con `npm install --save node-sass`
- [x] Tu proyecto no se ve correctamente en Github Pags porque falta una línea con `"homepage": "./",` en tu `package.json`.
- [x] Revisa los metadatos en `index.html` (`lang`, `title`...)
- [x] Usa un `<form>` para cada grupo de `<input>`, incluidos los filtros <https://github.com/Adalab/modulo-3-evaluacion-intermedia-AnadelaJara/blob/b6e02eaa322f63cd5a9b442edcc4fedff35b634f/src/components/App.js#L67-L74>
- [x] Elimina el código comentado, debuggers y consoles
- [x] Haz los bonus del ejercicio para que sigas practicando! 

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by AnadelaJara** [comment]
Hola Iván!! Hay algunas de las issues que me has puesto que no entiendo muy bien, como la primera en la que me dices que revise la aplicación de Chrome y donde arranco, que si hay fallos debo arreglarlo antes de continuar… No entiendo muy bien a qué te refieres, porque no me salía ningún error en la evaluación, y ahora lo he comprobado y tampoco… 
Me pasa algo parecido con la issue que me dices que no se ve bien en Github pages porque falta una línea con "homepage": "./", el caso es que se ve correctamente con Github Pages y revisando el package.json tengo correctamente la homepage…  No sé si te refieres a otra cosa...
Respecto a la issue de revisar los metadatos, he mirado y tengo tanto el Lang como el título cambiado, no se si te referías a otra cosa...
Las he marcado como hechas, si está mal me explicas y lo cambio :)

Muchas gracias!!! :)

**Comment by igarrido-adalab** [comment]
Lo de arrancar las DevTools siempre que trabajes con un proyecto React (o JavaScript) es una recomendación en general. Puedes hacerle check a esa línea.
Respecto a la de `"homepage": "./",` me temo que ha sido un error mío. Se me pasó al mirar el fichero `package.json`. Efectivamente, sí la tienes: <https://github.com/Adalab/modulo-3-evaluacion-intermedia-AnadelaJara/blob/b6e02eaa322f63cd5a9b442edcc4fedff35b634f/package.json#L3>. Otra que la puedes checkear, porque es error mío.
Y los metadatos... igual. Está todo correcto. Tienes tu `<title>` personalizado <https://github.com/Adalab/modulo-3-evaluacion-intermedia-AnadelaJara/blob/b6e02eaa322f63cd5a9b442edcc4fedff35b634f/public/index.html#L8> e, incluso, has puesto `lang="es"` en la etiqueta `<html>`: <https://github.com/Adalab/modulo-3-evaluacion-intermedia-AnadelaJara/blob/b6e02eaa322f63cd5a9b442edcc4fedff35b634f/public/index.html#L2>
Están todos los bonus ok. Incluso un estilo rosita muy chulo! Y, más difícil aún, las redes sociales de cada adalaber. Genial!

**Comment by igarrido-adalab** [comment]
Perfectísimo, @AnadelaJara
